# Generated by Django 5.1.5 on 2025-02-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='ni',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
